# Generated by Django 5.1.7 on 2025-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('High', 'Высокий'), ('Medium', 'Средний'), ('Low', 'Низкий')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Черновик'), ('Published', 'Опубликовано')], default='Draft', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
