# Generated by Django 5.2 on 2025-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_category_tag_entry_password_alter_entry_category_and_more'),
    ]

    operations = [
    ]
